[package]
edition = "2024"
name = "log-viewer"
version = "0.1.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
examples.workspace = true
freestyle-sculpt = { workspace = true, features = ["rerun", "serde"] }
glam = "0.33"
mesh-graph = { version = "*", features = [
    "rerun",
    "serde",
], path = "../../../mesh-graph" }
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
